### ISSUE TITLE
What is KB_ENDPOINT? 

### ISSUE THREAD

**Issue by globalexport** [Tiledesk/tiledesk#21]
Hi! 

What service url is expected in `KB_ENDPOINT` to scrape? I do not find documentation about it. 

Thank you!

**Comment by sponzillo** [comment]
Hi,  the KB (RAG chatbots) is actually only available on the SAAS version. It will come to the open source version for the end of April 🙏🏻

Andrea

**Comment by 0xM1gu3l** [comment]
Hey @globalexport, the KB_ENDPOINT is used to point to the [tiledesk-llm](https://github.com/Tiledesk/tiledesk-llm) project.
Just clone it to your machine and build it using Docker or pull the images at [Docker Hub](https://hub.docker.com/r/tiledesk/tiledesk-backend-llm).
Configured it today and it works like a charm!

**Comment by globalexport** [comment]
Thanks for the update! Now I understand it's a kind of API for the a pinecone vector db.

**Comment by globalexport** [comment]
It would be neat to see the tiledesk-llm one day working together with a local vector db like chroma or similar. Sometimes there are use cases which do not allow to store data on an external host.

**Comment by vi1world** [comment]
> Hey @globalexport, the KB_ENDPOINT is used to point to the [tiledesk-llm](https://github.com/Tiledesk/tiledesk-llm) project. Just clone it to your machine and build it using Docker or pull the images at [Docker Hub](https://hub.docker.com/r/tiledesk/tiledesk-backend-llm). Configured it today and it works like a charm!

Can you please share more details about your configuration? Thank you

**Comment by 0xM1gu3l** [comment]
> > Hey @globalexport, the KB_ENDPOINT is used to point to the [tiledesk-llm](https://github.com/Tiledesk/tiledesk-llm) project. Just clone it to your machine and build it using Docker or pull the images at [Docker Hub](https://hub.docker.com/r/tiledesk/tiledesk-backend-llm). Configured it today and it works like a charm!
> 
> Can you please share more details about your configuration? Thank you

Hey @vi1world, basically in your docker-compose file you need to add these lines under the service:

```yml
 tilellm:
    container_name: tilellm
    image: tiledesk/tiledesk-backend-llm:latest
    build: ./tiledesk-llm/
    ports:
      - "8000:8000"
    environment:
      - PINECONE_API_KEY={YOUR_API_KEY}
      - PINECONE_INDEX={YOUR_INDEX_NAME}
      - PINECONE_TEXT_KEY={TEXT_KEY}
```
You'll need a account on [Pinecone](https://www.pinecone.io/) to use the LLM
After that just replace the variables with your keys and you're good to go.

Note: The last time that I used this was 4 months ago so I don't know if it had any changes, but give it a try!
